# -*- coding: utf-8 -*-
"""Project Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tlcob6eKcEgmKDeg65LqT0rC0rrtWYyy

Fase 1: Persiapan Environment (Menyiapkan "Rumah")
Tujuannya adalah membuat file aplikasi (app.py) dan menyiapkan jalur agar bisa diakses dari laptopmu melalui browser.

1. Dapatkan API Key: Kunjungi Google AI Studio, buat API Key, dan simpan di Secrets (ikon Kunci) di sisi kiri Colab dengan nama GEMINI_API_KEY
2. Instal Library
3. uat File Utama: Gunakan perintah %%writefile untuk membuat file yang akan jadi "wajah" chatbot-mu
4. Menjalankan Web:
"""

pip install -q streamlit langchain langchain-google-genai google-generativeai requests faiss-cpu pypdf
npm install localtunnel

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# 
# st.title("🌤️ Test Chatbot Meteorologi")
# st.write("Jika halaman ini muncul, artinya Streamlit di Colab berhasil jalan!")

curl ipv4.icanhazip.com

streamlit run app.py & npx localtunnel --port 8501

"""Fase 2: Membangun Fungsi Tarik Data BMKG (Blok Tool 1)
Tujuannya adalah menciptakan alat agar AI bisa "mengetuk pintu" server BMKG dan mengambil data cuaca asli.

Konsep: Kita menggunakan requests untuk memanggil API resmi BMKG.

ara Kerja: Fungsi ini merubah JSON mentah dari BMKG menjadi teks yang rapi, sehingga Gemini bisa membacanya dengan mudah.
"""

import requests
import json

def cek_cuaca_bmkg(kode_wilayah: str) -> str:
    """
    Mengambil data prakiraan cuaca dari Open Data BMKG.
    Membutuhkan kode_wilayah tingkat IV (contoh Kemayoran: '31.71.03.1001').
    """
    url = f"https://api.bmkg.go.id/publik/prakiraan-cuaca?adm4={kode_wilayah}"

    try:
        # Mengirim permintaan ke server BMKG
        response = requests.get(url)
        response.raise_for_status() # Akan memicu error jika gagal (misal kena rate limit/salah kode)
        data = response.json()

        # Ekstraksi informasi lokasi
        lokasi = data['data'][0]['lokasi']

        # Ekstraksi prakiraan cuaca (Kita ambil 4 data pertama saja = 12 jam ke depan)
        # Tujuannya agar Gemini tidak kebingungan membaca data 3 hari sekaligus
        prakiraan = data['data'][0]['cuaca'][0][:4]

        # Gabungkan data yang relevan
        data_relevan = {
            "informasi_lokasi": lokasi,
            "prakiraan_cuaca": prakiraan
        }

        # Kembalikan dalam bentuk string JSON agar mudah dikunyah oleh Gemini
        return json.dumps(data_relevan, indent=2)

    except Exception as e:
        return f"Terjadi kesalahan saat mengambil data dari BMKG: {str(e)}"

# --- MARI KITA UJI COBA ---
# Kita gunakan kode wilayah Kemayoran yang kamu berikan sebelumnya
hasil_test = cek_cuaca_bmkg("31.71.03.1001")
print(hasil_test)

"""Fase 3: RAG (Mengajarkan AI Membaca Dokumen)
Di tahap ini, kita akan membuat skrip Python untuk memotong-motong halaman PDF menjadi paragraf-paragraf kecil, mengubahnya menjadi angka (Vektor Embedding), dan menyimpannya ke dalam database memori (FAISS).

Langkah-langkah Uji Coba Fase 3:

1. Siapkan File PDF: Siapkan satu fail PDF yang berisi materi meteorologi. Untuk pengujian, sangat cocok jika kamu menggunakan draf literatur yang membahas analisis Siklon Tropis Anggrek beserta dampaknya di sekitar perairan Banten dan Lampung, atau fail materi Hacktiv8.
2. Unggah ke Colab: * Di sebelah kiri layar Google Colab, klik ikon Folder (Files).
3. Klik ikon kertas dengan tanda panah ke atas (Upload).
4. Pilih fail PDF-mu. Tunggu sampai namanya muncul di daftar fail.
5. Buat Cell Baru: Gulir ke paling bawah Colab, buat satu + Code cell baru (pastikan cell Streamlit dan BMKG di atasnya dalam keadaan berhenti/stop).
6. Jalankan Skrip Ini: Copy-paste skrip di bawah ini. Sebelum menekan Play, ubah tulisan "nama_file_kamu.pdf" di bagian paling bawah skrip menjadi nama fail yang baru saja kamu unggah.
"""

pip install -q langchain-community pypdf

import os
from google.colab import userdata
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS

# (Gemini API Key tetap disiapkan untuk fase chat nanti)
os.environ["GOOGLE_API_KEY"] = userdata.get('GEMINI_API_KEY')

def setup_rag_pdf(pdf_path: str):
    print(f"Sedang membaca dokumen: {pdf_path}...")

    loader = PyPDFLoader(pdf_path)
    dokumen = loader.load()

    text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=200)
    chunks = text_splitter.split_documents(dokumen)
    print(f"Dokumen berhasil dipotong menjadi {len(chunks)} bagian teks kecil.")

    # KODE YANG MERUBAH SEGALANYA: Menggunakan model lokal HuggingFace
    print("Mengunduh model vektor lokal dan memproses dokumen (hanya butuh beberapa detik)...")
    embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")

    vector_db = FAISS.from_documents(chunks, embeddings)
    print("✅ Database Vektor berhasil dibuat dan siap digunakan!")

    return vector_db

# ==========================================
# --- MARI KITA UJI COBA PENCARIAN RAG ---
# ==========================================

NAMA_FILE_PDF = "BAHAN AJAR AGENDA 1 OBSERVASI FENOMENA DAN PARAMETER METEOROLOGI PENERBANGAN.pdf"

database_pengetahuan = setup_rag_pdf(NAMA_FILE_PDF)

query_pertanyaan = "Apa saja parameter meteorologi yang paling penting untuk diamati dalam kegiatan penerbangan?"
print(f"\nMencari jawaban untuk: '{query_pertanyaan}'")

hasil_pencarian = database_pengetahuan.similarity_search(query_pertanyaan, k=2)

print("\n--- HASIL POTONGAN TEKS YANG DITEMUKAN ---")
for i, dokumen in enumerate(hasil_pencarian):
    print(f"\nPotongan ke-{i+1} (Halaman {dokumen.metadata.get('page', 'Tidak diketahui')}):")
    print(dokumen.page_content)

"""Fase 4: Merakit "Otak" AI Agent
Di fase ini, kita akan menghubungkan model bahasa (Gemini 1.5 Flash) dengan dua alat bantu yang sudah kamu buat tadi. Kita akan menggunakan fitur LangChain yang disebut Tools.

Nantinya, kita akan memberikan instruksi ketat kepada Gemini:

"Kalau ditanya teori, gunakan alat baca PDF."

"Kalau ditanya cuaca, gunakan alat penarik JSON BMKG.

"""

pip install -q \
  langchain==1.0.1 \
  langchain-core==1.0.0 \
  langchain-classic==1.0.0 \
  langchain-community==0.4 \
  langchain-google-genai==3.0.0 \
  langchain-text-splitters==0.3.11 \
  pypdf \
  faiss-cpu \
  sentence-transformers

# ==========================================
# FASE 4: MERAKIT "OTAK" AI AGENT (REVISI FINAL)
# ==========================================

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_classic.agents import AgentExecutor, create_tool_calling_agent
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.tools import tool

# ------------------------------------------
# 1. Inisialisasi Otak Utama (Gemini 3.5 Flash)
# ------------------------------------------
# Catatan: gemini-1.5-flash sudah di-shutdown Google per 2026.
# gemini-3.5-flash adalah versi GA terbaru, dioptimalkan untuk agentic & tool-calling.
llm = ChatGoogleGenerativeAI(model="gemini-3.5-flash", temperature=0.1)

# ------------------------------------------
# 2. Tool 1 — Wrapper untuk fungsi BMKG (Fase 2)
# ------------------------------------------
@tool
def alat_cek_cuaca(kode_wilayah: str) -> str:
    """
    Gunakan alat ini HANYA JIKA pengguna menanyakan prakiraan cuaca atau kondisi cuaca harian di suatu wilayah.
    Input harus berupa kode wilayah tingkat IV (adm4), contoh: '31.71.03.1001'.
    """
    return cek_cuaca_bmkg(kode_wilayah)  # reuse fungsi dari Fase 2, jangan tulis ulang logic

# ------------------------------------------
# 3. Tool 2 — Wrapper untuk vectorstore RAG (Fase 3)
# ------------------------------------------
@tool
def alat_baca_pdf(pertanyaan: str) -> str:
    """
    Gunakan alat ini JIKA pengguna menanyakan teori, regulasi, definisi, atau observasi
    fenomena meteorologi penerbangan yang bersumber dari dokumen bahan ajar.
    """
    hasil = database_pengetahuan.similarity_search(pertanyaan, k=2)
    teks_gabungan = "\n\n".join(
        f"[Halaman {doc.metadata.get('page', '?')}] {doc.page_content}" for doc in hasil
    )
    return teks_gabungan

# ------------------------------------------
# 4. Rakit Agent
# ------------------------------------------
daftar_alat = [alat_cek_cuaca, alat_baca_pdf]

prompt = ChatPromptTemplate.from_messages([
    ("system",
     "Kamu adalah asisten ahli meteorologi penerbangan. "
     "Gunakan alat bantu yang tersedia untuk menjawab pertanyaan pengguna dengan akurat. "
     "Jika pertanyaan tentang cuaca aktual/prakiraan, gunakan alat_cek_cuaca. "
     "Jika pertanyaan tentang teori/regulasi/definisi, gunakan alat_baca_pdf."),
    ("human", "{input}"),
    ("placeholder", "{agent_scratchpad}"),
])

agen = create_tool_calling_agent(llm, daftar_alat, prompt)
agen_cuaca = AgentExecutor(agent=agen, tools=daftar_alat, verbose=True)

# ------------------------------------------
# 5. Helper — Ekstraksi output bersih
# ------------------------------------------
def ekstrak_teks_jawaban(output_agent) -> str:
    """
    Menangani perbedaan format output antar versi model Gemini.
    Gemini 3.x mengembalikan output sebagai list of content blocks (karena reasoning/thinking
    internal model), sedangkan versi lama mengembalikan string langsung.
    Fungsi ini menyeragamkan keduanya menjadi string biasa siap-tampil.
    """
    if isinstance(output_agent, str):
        return output_agent
    if isinstance(output_agent, list):
        return "\n".join(
            block.get("text", "")
            for block in output_agent
            if isinstance(block, dict) and block.get("type") == "text"
        )
    return str(output_agent)

# ==========================================
# --- UJI COBA KECERDASAN AGEN ---
# ==========================================

print("\n\n--- TEST 1: BERTANYA TEORI (Harus memicu alat_baca_pdf) ---")
jawaban_teori = agen_cuaca.invoke({
    "input": "Berdasarkan dokumen, apa saja parameter meteorologi yang paling penting untuk diamati dalam kegiatan penerbangan?"
})
print("\nJAWABAN FINAL TEST 1:\n", ekstrak_teks_jawaban(jawaban_teori['output']))

print("\n\n------------------------------------------------------------\n")

print("\n--- TEST 2: BERTANYA CUACA (Harus memicu alat_cek_cuaca) ---")
jawaban_cuaca = agen_cuaca.invoke({
    "input": "Tolong cek prakiraan cuaca di Kemayoran (kode wilayah: 31.71.03.1001) hari ini."
})
print("\nJAWABAN FINAL TEST 2:\n", ekstrak_teks_jawaban(jawaban_cuaca['output']))

"""Fase 5: Membangun Antarmuka ui ux secara non back end dan telah berhasil untuk melihat ui ux terbarunya"""

pip install -q streamlit
npm install -g localtunnel

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import time
# 
# st.set_page_config(page_title="Cuacaku", page_icon="🌤️", layout="wide")
# 
# # ------------------------------------------
# # CUSTOM CSS
# # ------------------------------------------
# st.markdown("""
# <style>
#     .badge-cuaca {
#         background-color: #E6F1FB; color: #0C447C;
#         padding: 4px 10px; border-radius: 8px; font-size: 12px;
#         display: inline-flex; align-items: center; gap: 4px;
#     }
#     .badge-info {
#         background-color: #EAF3DE; color: #27500A;
#         padding: 4px 10px; border-radius: 8px; font-size: 12px;
#         display: inline-flex; align-items: center; gap: 4px;
#     }
#     .subtitle-text {
#         color: #6B6B6B; font-size: 13px; margin-top: 0px;
#     }
# </style>
# """, unsafe_allow_html=True)
# 
# # ------------------------------------------
# # HEADER - Logo STMKG + BMKG bersebelahan
# # ------------------------------------------
# col_logo1, col_logo2, col_title = st.columns([1, 1, 8])
# 
# with col_logo1:
#     try:
#         st.image("Lambang-Logo-STMKG.jpg", width=55)
#     except Exception:
#         st.markdown("`[Logo STMKG]`")
# 
# with col_logo2:
#     try:
#         st.image("Logo-BMKG png.png", width=55)
#     except Exception:
#         st.markdown("`[Logo BMKG]`")
# 
# with col_title:
#     st.markdown("### 🌤️ Cuacaku")
#     st.markdown(
#         '<p class="subtitle-text">Membantu memberi informasi meteorologi dan '
#         'prakiraan cuacamu! (sumber data BMKG)</p>',
#         unsafe_allow_html=True
#     )
# 
# st.markdown(
#     '<span class="badge-cuaca">☁️ Cuaca</span> &nbsp; '
#     '<span class="badge-info">📖 Info umum</span>',
#     unsafe_allow_html=True
# )
# 
# st.divider()
# 
# # ------------------------------------------
# # SIDEBAR
# # ------------------------------------------
# with st.sidebar:
#     st.markdown("#### Cuacaku")
# 
#     if st.button("➕ Chat baru", use_container_width=True):
#         st.session_state.messages = []
#         st.rerun()
# 
#     uploaded_pdf = st.file_uploader("📎 Upload dokumen (PDF)", type="pdf")
#     if uploaded_pdf:
#         st.success(f"'{uploaded_pdf.name}' siap dipelajari (dummy - belum diproses ke RAG).")
# 
#     st.markdown("---")
#     st.markdown("**Riwayat**")
#     st.markdown("- Cuaca Kemayoran hari ini")
#     st.markdown("- Parameter observer WMO")
#     st.markdown("- Definisi METAR SPECI")
# 
#     st.markdown("---")
#     st.caption("👤 Rafi")
# 
# # ------------------------------------------
# # STATE
# # ------------------------------------------
# if "messages" not in st.session_state:
#     st.session_state.messages = []
# 
# # ------------------------------------------
# # CHIP SARAN PERTANYAAN
# # ------------------------------------------
# if not st.session_state.messages:
#     st.markdown("**Coba tanyakan:**")
#     chip_col1, chip_col2, chip_col3 = st.columns(3)
#     contoh_pertanyaan = None
#     with chip_col1:
#         if st.button("☀️ Cuaca hari ini di wilayahku"):
#             contoh_pertanyaan = "Cuaca hari ini di wilayahku"
#     with chip_col2:
#         if st.button("💨 Apa itu wind shear?"):
#             contoh_pertanyaan = "Apa itu wind shear?"
#     with chip_col3:
#         if st.button("🌩️ Jenis-jenis awan konvektif"):
#             contoh_pertanyaan = "Jenis-jenis awan konvektif"
# else:
#     contoh_pertanyaan = None
# 
# # ------------------------------------------
# # RENDER RIWAYAT CHAT
# # ------------------------------------------
# for msg in st.session_state.messages:
#     with st.chat_message(msg["role"]):
#         if msg["role"] == "assistant" and msg.get("tool"):
#             with st.expander("🔧 Lihat proses tool-calling"):
#                 st.code(msg["tool"], language="text")
#         st.markdown(msg["content"])
# 
# # ------------------------------------------
# # LOGIC DUMMY
# # ------------------------------------------
# def jawaban_dummy(pertanyaan: str):
#     kata_cuaca = ["cuaca", "suhu", "hujan", "angin", "kelembapan", "wilayah"]
#     if any(k in pertanyaan.lower() for k in kata_cuaca):
#         tool_trace = "alat_cek_cuaca(kode_wilayah='31.71.03.1001')"
#         jawaban = (
#             "Cerah, 29°C, kelembapan 68%, angin dari timur laut 11 km/jam. "
#             "Visibility >10 km — kondisi mendukung aktivitas luar ruangan. "
#             "*(contoh jawaban dummy)*"
#         )
#     else:
#         tool_trace = "alat_baca_pdf(pertanyaan='...')"
#         jawaban = (
#             "Berdasarkan basis pengetahuan, parameter penting meliputi angin, "
#             "visibility, tipe awan, suhu, dan tekanan udara. "
#             "*(contoh jawaban dummy)*"
#         )
#     return jawaban, tool_trace
# 
# # ------------------------------------------
# # INPUT USER
# # ------------------------------------------
# input_user = st.chat_input("Tanyakan cuaca atau info meteorologi...")
# pesan_final = input_user or contoh_pertanyaan
# 
# if pesan_final:
#     st.session_state.messages.append({"role": "user", "content": pesan_final})
#     with st.chat_message("user"):
#         st.markdown(pesan_final)
# 
#     with st.chat_message("assistant"):
#         with st.spinner("Cuacaku sedang berpikir..."):
#             time.sleep(0.8)
#             jawaban, tool_trace = jawaban_dummy(pesan_final)
# 
#         with st.expander("🔧 Lihat proses tool-calling"):
#             st.code(tool_trace, language="text")
#         st.markdown(jawaban)
# 
#     st.session_state.messages.append({
#         "role": "assistant",
#         "content": jawaban,
#         "tool": tool_trace
#     })
#     st.rerun()

cat app.py | head -5

pkill -f streamlit
pkill -f localtunnel

# Cell 5 — revisi, kedua proses di-background ke file log terpisah
streamlit run app.py --server.enableCORS false --server.enableXsrfProtection false &> /content/streamlit_log.txt &
npx localtunnel --port 8501 &> /content/tunnel_log.txt &

import time
time.sleep(8)  # beri waktu proses mulai sebelum lanjut
print("✅ Kedua proses sudah jalan di background. Cell ini akan langsung selesai (tidak loading terus).")

# Cell 6 — baru dijalankan SETELAH Cell 5, karena sekarang bisa berurutan normal
print("=== URL Tunnel ===")
grep "your url" /content/tunnel_log.txt

print("\n=== Info IP (untuk verifikasi tunnel password) ===")
grep "External URL" /content/streamlit_log.txt

# Cell — bersihkan proses lama dulu
pkill -f streamlit

# Cell — jalankan Streamlit di background
streamlit run app.py --server.enableCORS false --server.enableXsrfProtection false &> /content/streamlit_log.txt &

import time
time.sleep(6)

# Cell — buka lewat proxy native Colab (GANTI localtunnel sepenuhnya)
from google.colab.output import eval_js
print(eval_js("google.colab.kernel.proxyPort(8501)"))

"""Fase 6: Membangun Antarmuka (Streamlit) & Publikasi
Tujuan: Merapikan tampilan agar mudah digunakan dan bisa diakses orang lain.

Aksi: 1. Mendesain tampilan chatbot di Streamlit (kotak input, riwayat percakapan).
2. Menghubungkan logika Agent (dari Fase 4) ke dalam komponen chat di Streamlit.
3. Memastikan website stabil dan siap digunakan untuk presentasi.

Catatan untukmu, Rafi: Karena kita sudah berhasil melakukan Fase 1-3 dengan lancar, sekarang kita tinggal memfokuskan perbaikan pada Fase 4 (perakitan Agent). Setelah Agent-nya "pintar" memilih alat, kita akan langsung melompat ke Fase 6 untuk menyatukan semuanya ke dalam tampilan website yang cantik!

"""

pip install -q \
  streamlit \
  langchain==1.0.1 \
  langchain-core==1.0.0 \
  langchain-classic==1.0.0 \
  langchain-community==0.4 \
  langchain-google-genai==3.0.0 \
  langchain-text-splitters==0.3.11 \
  pypdf faiss-cpu sentence-transformers requests

import os
from google.colab import userdata
os.environ["GEMINI_API_KEY"] = userdata.get('GEMINI_API_KEY')

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import time
# import os
# import json
# import requests
# import tempfile
# 
# from langchain_google_genai import ChatGoogleGenerativeAI
# from langchain_classic.agents import AgentExecutor, create_tool_calling_agent
# from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
# from langchain_core.tools import tool
# from langchain_core.messages import HumanMessage, AIMessage
# from langchain_community.document_loaders import PyPDFLoader
# from langchain_text_splitters import RecursiveCharacterTextSplitter
# from langchain_community.embeddings import HuggingFaceEmbeddings
# from langchain_community.vectorstores import FAISS
# 
# st.set_page_config(page_title="Cuacaku", page_icon="🌤️", layout="wide")
# 
# # ------------------------------------------
# # KONFIGURASI
# # ------------------------------------------
# os.environ["GOOGLE_API_KEY"] = os.environ.get("GEMINI_API_KEY", "")
# NAMA_FILE_PDF = "BAHAN AJAR AGENDA 1 OBSERVASI FENOMENA DAN PARAMETER METEOROLOGI PENERBANGAN.pdf"
# 
# # ------------------------------------------
# # CUSTOM CSS (dari Fase 5)
# # ------------------------------------------
# st.markdown("""
# <style>
#     .badge-cuaca {
#         background-color: #E6F1FB; color: #0C447C;
#         padding: 4px 10px; border-radius: 8px; font-size: 12px;
#         display: inline-flex; align-items: center; gap: 4px;
#     }
#     .badge-info {
#         background-color: #EAF3DE; color: #27500A;
#         padding: 4px 10px; border-radius: 8px; font-size: 12px;
#         display: inline-flex; align-items: center; gap: 4px;
#     }
#     .subtitle-text {
#         color: #6B6B6B; font-size: 13px; margin-top: 0px;
#     }
# </style>
# """, unsafe_allow_html=True)
# 
# # ------------------------------------------
# # FUNGSI FASE 2 — BMKG
# # ------------------------------------------
# def cek_cuaca_bmkg(kode_wilayah: str) -> str:
#     url = f"https://api.bmkg.go.id/publik/prakiraan-cuaca?adm4={kode_wilayah}"
#     try:
#         response = requests.get(url, timeout=10)
#         response.raise_for_status()
#         data = response.json()
#         lokasi = data['data'][0]['lokasi']
#         prakiraan = data['data'][0]['cuaca'][0][:4]
#         return json.dumps({"informasi_lokasi": lokasi, "prakiraan_cuaca": prakiraan}, indent=2)
#     except Exception as e:
#         return f"Terjadi kesalahan saat mengambil data dari BMKG: {str(e)}"
# 
# # ------------------------------------------
# # FUNGSI FASE 3 — RAG (di-cache supaya tidak rebuild tiap rerun)
# # ------------------------------------------
# @st.cache_resource(show_spinner="Membangun basis pengetahuan dari PDF...")
# def setup_rag_pdf(pdf_path: str):
#     loader = PyPDFLoader(pdf_path)
#     dokumen = loader.load()
#     text_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=200)
#     chunks = text_splitter.split_documents(dokumen)
#     embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")
#     return FAISS.from_documents(chunks, embeddings)
# 
# database_pengetahuan = setup_rag_pdf(NAMA_FILE_PDF)
# 
# # ------------------------------------------
# # TOOLS FASE 4
# # ------------------------------------------
# @tool
# def alat_cek_cuaca(kode_wilayah: str) -> str:
#     """
#     Gunakan alat ini HANYA JIKA pengguna menanyakan prakiraan cuaca atau kondisi cuaca harian di suatu wilayah.
#     Input harus berupa kode wilayah tingkat IV (adm4), contoh: '31.71.03.1001'.
#     """
#     return cek_cuaca_bmkg(kode_wilayah)
# 
# @tool
# def alat_baca_pdf(pertanyaan: str) -> str:
#     """
#     Gunakan alat ini JIKA pengguna menanyakan teori, regulasi, definisi, atau observasi
#     fenomena meteorologi yang bersumber dari dokumen bahan ajar.
#     """
#     hasil = database_pengetahuan.similarity_search(pertanyaan, k=2)
#     return "\n\n".join(
#         f"[Halaman {doc.metadata.get('page', '?')}] {doc.page_content}" for doc in hasil
#     )
# 
# daftar_alat = [alat_cek_cuaca, alat_baca_pdf]
# 
# # ------------------------------------------
# # PROMPT — dengan chat_history untuk multi-turn
# # ------------------------------------------
# prompt = ChatPromptTemplate.from_messages([
#     ("system",
#      "Kamu adalah Cuacaku, asisten meteorologi yang ramah dan informatif. "
#      "Kamu bisa menjawab soal cuaca real-time maupun teori/pengetahuan meteorologi umum. "
#      "Jika pertanyaan tentang cuaca aktual/prakiraan, gunakan alat_cek_cuaca. "
#      "Jika pertanyaan tentang teori/regulasi/definisi/awan/fenomena atmosfer, gunakan alat_baca_pdf. "
#      "Perhatikan riwayat percakapan sebelumnya untuk memahami konteks pertanyaan lanjutan."),
#     MessagesPlaceholder(variable_name="chat_history"),
#     ("human", "{input}"),
#     ("placeholder", "{agent_scratchpad}"),
# ])
# 
# @st.cache_resource(show_spinner="Menyiapkan AI Agent...")
# def buat_agent():
#     llm = ChatGoogleGenerativeAI(model="gemini-3.5-flash", temperature=0.1)
#     agen = create_tool_calling_agent(llm, daftar_alat, prompt)
#     return AgentExecutor(agent=agen, tools=daftar_alat, verbose=True, return_intermediate_steps=True)
# 
# agen_cuaca = buat_agent()
# 
# def ekstrak_teks_jawaban(output_agent) -> str:
#     if isinstance(output_agent, str):
#         return output_agent
#     if isinstance(output_agent, list):
#         return "\n".join(
#             block.get("text", "") for block in output_agent
#             if isinstance(block, dict) and block.get("type") == "text"
#         )
#     return str(output_agent)
# 
# # ------------------------------------------
# # HEADER — logo STMKG + BMKG
# # ------------------------------------------
# col_logo1, col_logo2, col_title = st.columns([1, 1, 8])
# with col_logo1:
#     try:
#         st.image("Lambang-Logo-STMKG.jpg", width=55)
#     except Exception:
#         st.markdown("`[Logo STMKG]`")
# with col_logo2:
#     try:
#         st.image("Logo-BMKG png.png", width=55)
#     except Exception:
#         st.markdown("`[Logo BMKG]`")
# with col_title:
#     st.markdown("### 🌤️ Cuacaku")
#     st.markdown(
#         '<p class="subtitle-text">Membantu memberi informasi meteorologi dan '
#         'prakiraan cuacamu! (sumber data BMKG)</p>',
#         unsafe_allow_html=True
#     )
# 
# st.markdown(
#     '<span class="badge-cuaca">☁️ Cuaca</span> &nbsp; '
#     '<span class="badge-info">📖 Info umum</span>',
#     unsafe_allow_html=True
# )
# st.divider()
# 
# # ------------------------------------------
# # SIDEBAR — upload PDF SEKARANG DIPROSES BENERAN ke FAISS
# # ------------------------------------------
# with st.sidebar:
#     st.markdown("#### Cuacaku")
# 
#     if st.button("➕ Chat baru", use_container_width=True):
#         st.session_state.messages = []
#         st.session_state.chat_history = []
#         st.rerun()
# 
#     uploaded_pdf = st.file_uploader("📎 Upload dokumen tambahan (PDF)", type="pdf")
#     if uploaded_pdf and uploaded_pdf.name != st.session_state.get("pdf_terakhir_diproses"):
#         with st.spinner(f"Mempelajari '{uploaded_pdf.name}'..."):
#             with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as tmp:
#                 tmp.write(uploaded_pdf.read())
#                 tmp_path = tmp.name
# 
#             loader_baru = PyPDFLoader(tmp_path)
#             dokumen_baru = loader_baru.load()
#             splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=200)
#             chunks_baru = splitter.split_documents(dokumen_baru)
#             embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")
#             db_baru = FAISS.from_documents(chunks_baru, embeddings)
# 
#             database_pengetahuan.merge_from(db_baru)  # gabung ke index utama
#             st.session_state.pdf_terakhir_diproses = uploaded_pdf.name
# 
#         st.success(f"'{uploaded_pdf.name}' berhasil dipelajari dan digabung ke basis pengetahuan!")
# 
#     st.markdown("---")
#     st.markdown("**Riwayat**")
#     for m in st.session_state.get("messages", [])[-6:]:
#         if m["role"] == "user":
#             st.markdown(f"- {m['content'][:40]}")
# 
#     st.markdown("---")
#     st.caption("👤 Rafi")
# 
# # ------------------------------------------
# # STATE
# # ------------------------------------------
# if "messages" not in st.session_state:
#     st.session_state.messages = []
# if "chat_history" not in st.session_state:
#     st.session_state.chat_history = []
# 
# # ------------------------------------------
# # CHIP SARAN PERTANYAAN
# # ------------------------------------------
# contoh_pertanyaan = None
# if not st.session_state.messages:
#     st.markdown("**Coba tanyakan:**")
#     c1, c2, c3 = st.columns(3)
#     with c1:
#         if st.button("☀️ Cuaca hari ini di Kemayoran"):
#             contoh_pertanyaan = "Cuaca hari ini di Kemayoran (kode wilayah 31.71.03.1001)"
#     with c2:
#         if st.button("💨 Apa itu wind shear?"):
#             contoh_pertanyaan = "Apa itu wind shear?"
#     with c3:
#         if st.button("🌩️ Jenis-jenis awan konvektif"):
#             contoh_pertanyaan = "Apa saja jenis-jenis awan konvektif?"
# 
# # ------------------------------------------
# # RENDER RIWAYAT CHAT
# # ------------------------------------------
# for msg in st.session_state.messages:
#     with st.chat_message(msg["role"]):
#         if msg["role"] == "assistant" and msg.get("steps"):
#             with st.expander("🔧 Lihat proses tool-calling"):
#                 for i, (aksi, hasil_tool) in enumerate(msg["steps"], 1):
#                     st.markdown(f"**Langkah {i}: `{aksi.tool}`**")
#                     st.code(json.dumps(aksi.tool_input, ensure_ascii=False), language="json")
#         st.markdown(msg["content"])
# 
# # ------------------------------------------
# # INPUT USER — SEKARANG PANGGIL AGENT ASLI
# # ------------------------------------------
# input_user = st.chat_input("Tanyakan cuaca atau info meteorologi...")
# pesan_final = input_user or contoh_pertanyaan
# 
# if pesan_final:
#     st.session_state.messages.append({"role": "user", "content": pesan_final})
#     with st.chat_message("user"):
#         st.markdown(pesan_final)
# 
#     with st.chat_message("assistant"):
#         with st.spinner("Cuacaku sedang berpikir..."):
#             respons = agen_cuaca.invoke({
#                 "input": pesan_final,
#                 "chat_history": st.session_state.chat_history
#             })
#         jawaban = ekstrak_teks_jawaban(respons["output"])
#         steps = respons.get("intermediate_steps", [])
# 
#         if steps:
#             with st.expander("🔧 Lihat proses tool-calling", expanded=True):
#                 for i, (aksi, hasil_tool) in enumerate(steps, 1):
#                     st.markdown(f"**Langkah {i}: `{aksi.tool}`**")
#                     st.code(json.dumps(aksi.tool_input, ensure_ascii=False), language="json")
#         st.markdown(jawaban)
# 
#     st.session_state.messages.append({"role": "assistant", "content": jawaban, "steps": steps})
#     st.session_state.chat_history.append(HumanMessage(content=pesan_final))
#     st.session_state.chat_history.append(AIMessage(content=jawaban))
#     if len(st.session_state.chat_history) > 10:
#         st.session_state.chat_history = st.session_state.chat_history[-10:]
# 
#     st.rerun()

pkill -f streamlit

streamlit run app.py --server.enableCORS false --server.enableXsrfProtection false &> /content/streamlit_log.txt &
import time
time.sleep(6)

from google.colab.output import eval_js
print(eval_js("google.colab.kernel.proxyPort(8501)"))
